'use client';

import { useState } from 'react';
import GraphVisualization from '@/components/GraphVisualization';
import FileUpload from '@/components/FileUpload';
import { parseDOT } from '@/lib/dotParser';
import { Node, Edge } from 'reactflow';

interface GraphData {
  nodes: Node[];
  edges: Edge[];
}

export default function Home() {
  const [graphData, setGraphData] = useState<GraphData | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleFileContent = async (content: string) => {
    setLoading(true);
    setError(null);
    
    try {
      const { nodes, edges } = parseDOT(content);
      setGraphData({ nodes, edges });
    } catch (err) {
      setError('Failed to parse DOT file. Please check the format.');
      console.error('Parse error:', err);
    } finally {
      setLoading(false);
    }
  };

  const resetGraph = () => {
    setGraphData(null);
    setError(null);
  };

  return (
    <div className="h-screen flex flex-col bg-gray-100">
      <header className="bg-white shadow-sm border-b flex-shrink-0">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center py-4">
            <div className="flex items-center gap-8">
              <h1 className="text-2xl font-bold text-gray-900">Cartographer</h1>
              {graphData && (
                <div className="text-sm text-gray-600">
                  {graphData.nodes.length} functions, {graphData.edges.length} connections
                </div>
              )}
            </div>
            {graphData && (
              <button
                onClick={resetGraph}
                className="px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition-colors"
              >
                Load New Graph
              </button>
            )}
          </div>
        </div>
      </header>

      <main className="flex-1 overflow-hidden">
        {!graphData ? (
          <div className="h-full flex items-center justify-center">
            <div className="max-w-2xl mx-auto p-8">
              <div className="bg-white rounded-lg shadow-sm p-8">
                <div className="text-center mb-8">
                  <h2 className="text-xl font-semibold text-gray-900 mb-2">
                    Visualize Your Go Code Dependencies
                  </h2>
                  <p className="text-gray-600">
                    Upload a DOT file generated by the Cartographer CLI tool to see an interactive graph
                    with AI-powered explanations.
                  </p>
                </div>
                
                {error && (
                  <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg">
                    <p className="text-red-800">{error}</p>
                  </div>
                )}
                
                {loading ? (
                  <div className="text-center py-8">
                    <div className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
                    <p className="mt-2 text-gray-600">Processing graph...</p>
                  </div>
                ) : (
                  <FileUpload onFileContent={handleFileContent} />
                )}
              </div>
            </div>
          </div>
        ) : (
          <div className="h-full">
            <GraphVisualization 
              nodes={graphData.nodes} 
              edges={graphData.edges} 
            />
          </div>
        )}
      </main>
    </div>
  );
}
