'use client';

import { useState, useEffect } from 'react';
import GraphVisualization from '@/components/GraphVisualization';
import FileUpload from '@/components/FileUpload';
import { parseDOT } from '@/lib/dotParser';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Sun, Moon, Workflow, RotateCcw } from 'lucide-react';
import type { Node, Edge } from '@xyflow/react';

interface GraphData {
  nodes: Node[];
  edges: Edge[];
  callGraph: Map<string, string[]>;
  reverseCallGraph: Map<string, string[]>;
}

export default function Home() {
  const [graphData, setGraphData] = useState<GraphData | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isDark, setIsDark] = useState(false);
  const [isHighlightMode, setIsHighlightMode] = useState(false);

  // Load dark mode preference from localStorage
  useEffect(() => {
    const saved = localStorage.getItem('darkMode');
    if (saved) {
      setIsDark(JSON.parse(saved));
    }
  }, []);

  // Update localStorage and document class when dark mode changes
  useEffect(() => {
    localStorage.setItem('darkMode', JSON.stringify(isDark));
    if (isDark) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [isDark]);

  const handleFileContent = async (content: string) => {
    setLoading(true);
    setError(null);
    
    try {
      const { nodes, edges, callGraph, reverseCallGraph } = parseDOT(content);
      // Add dark mode info to node data
      const nodesWithDarkMode = nodes.map(node => ({
        ...node,
        data: { ...node.data, isDark }
      }));
      setGraphData({ nodes: nodesWithDarkMode, edges, callGraph, reverseCallGraph });
    } catch (err) {
      setError('Failed to parse DOT file. Please check the format.');
      console.error('Parse error:', err);
    } finally {
      setLoading(false);
    }
  };

  const resetGraph = () => {
    setGraphData(null);
    setError(null);
    setIsHighlightMode(false);
  };

  const toggleDarkMode = () => {
    setIsDark(!isDark);
  };

  const toggleHighlightMode = () => {
    setIsHighlightMode(!isHighlightMode);
  };

  return (
    <div className="h-screen flex flex-col bg-background">
      <header className="border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 flex-shrink-0">
        <div className="lg:px-4">
          <div className="flex items-center py-3">
            <div className="flex-1 flex items-center">
              <h1 className="text-md font-medium text-foreground">
                Cartographer
              </h1>
            </div>
            <div className="flex-1 text-center text-sm text-muted-foreground">
              {graphData && `${graphData.nodes.length} functions, ${graphData.edges.length} connections`}
            </div>
            <div className="flex-1 flex items-center justify-end gap-4">
              <Button
                variant="ghost"
                size="icon"
                onClick={toggleDarkMode}
                className="h-9 w-9"
              >
                {isDark ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}
              </Button>
              {graphData && (
                <Button
                  variant={isHighlightMode ? "default" : "outline"}
                  onClick={toggleHighlightMode}
                  className="gap-2"
                >
                  <Workflow className="h-4 w-4" />
                  Highlight Mode
                </Button>
              )}
              {graphData && (
                <Button onClick={resetGraph} variant="outline" className="gap-2">
                  <RotateCcw className="h-4 w-4" />
                  Load New Graph
                </Button>
              )}
            </div>
          </div>
        </div>
      </header>

      <main className="flex-1 overflow-hidden">
        {!graphData ? (
          <div className="h-full flex items-center justify-center p-8">
            <div className="max-w-2xl mx-auto w-full">
              <Card>
                <CardHeader className="text-center">
                  <CardTitle className="text-2xl">
                    Visualize Your Go Code Dependencies
                  </CardTitle>
                  <CardDescription>
                    Upload a DOT file generated by the Cartographer CLI tool to see an interactive graph
                    with AI-powered explanations.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  {error && (
                    <Alert variant="destructive" className="mb-6">
                      <AlertDescription>{error}</AlertDescription>
                    </Alert>
                  )}
                  
                  {loading ? (
                    <div className="text-center py-8">
                      <div className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
                      <p className="mt-2 text-muted-foreground">
                        Processing graph...
                      </p>
                    </div>
                  ) : (
                    <FileUpload onFileContent={handleFileContent} />
                  )}
                </CardContent>
              </Card>
            </div>
          </div>
        ) : (
          <div className="h-full">
            <GraphVisualization 
              nodes={graphData.nodes} 
              edges={graphData.edges}
              isDark={isDark}
              isHighlightMode={isHighlightMode}
              callGraph={graphData.callGraph}
              reverseCallGraph={graphData.reverseCallGraph}
            />
          </div>
        )}
      </main>
    </div>
  );
}
